### PR TITLE
feat(fortune): allow max_width to be changed

### PR DESCRIPTION
**Pull request by Shivix**
This allows the max width of quote messages to be easily changed in a
config

### CODE REVIEW

**Comment by Shivix** [comment]
Couldn't think of a good name for `width` I'm happy to change if you think of something better.

**Comment by goolord** [comment]
name it `max_width` and remove `local` so it mutates `max_width`
also add a luadoc for the parameter please :3

**Comment by Shivix** [comment]
Oh perfect, good thinking. 
Not used to luadoc, let me know if it's okay.

**Comment by goolord** [comment]
lgtm, thanks for all of your contributions 🖤

**Pull request merged**
